recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
        - osxdefaults::set_screensaver_preferences
        - macapps::dropbox
        - macapps::firefox
        - macapps::spotify
        - macapps::vagrant
        - macapps::virtualbox
        - hipchat_client
    homebrewalt:
        apps:
            - git
        cask_apps:
            - google-chrome
    nodejs:
        apps:
            - bower
