groups:
    - groupb
recipes:
    mac_os_x:
        - osxdefaults::set_terminal_profile
        - applications::sublime_text_3
attributes:
    homebrewalt:
        apps:
            - git-extras
        cask_apps:
            - sourcetree
